version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: wsf-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: wsf-ia
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5433:5432"
    volumes:
      - wschedflow_pgdata:/var/lib/postgresql/data

volumes:
  wschedflow_pgdata:
