spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5433/wsf-ia
    username: admin
    password: admin

  flyway:
    enabled: true
    url: jdbc:postgresql://localhost:5433/wsf-ia
    user: admin
    password: admin

logging:
  level:
    org.springframework.r2dbc: DEBUG
